nosana:
  description: "Template Repo Pipeline"

global:
  image: node:18

  trigger:
    branch:
      - main

  environment:
    NPM_PAT: "test"
      
jobs:
  - name: "Install Dependencies"
    commands:
      - npm ci
      - npm run lint
      - npm run build
      - npm run test