nosana:
  description: "Template Repo Pipeline"
  
global:
  image: registry.hub.docker.com/library/node:18

  trigger:
    branch:
      - main
      
      
  environment:
    NPM_TOKEN:
      type: "nosana/secret"
      endpoint: "https://secrets.k8s.dev.nos.ci"
      value: "npm-deploy-key"
      
jobs:
  - name: "Install Dependencies"
    commands:
      - ls
      - npm ci