nosana:
  description: "Template Repo Pipeline"

global:
  image: node:18

  trigger:
    branch:
      - main

  environment:
    TEST:
      type: "nosana/secret"
      endpoint: "https://secrets.k8s.dev.nos.ci"
      value: "ENV"
      
jobs:
  - name: "Install Dependencies"
    commands:
      - echo $TEST
      - npm ci
      - npm run lint
      - npm run build
      - npm run test