nosana:
  description: "Template Repo Pipeline"
  

global:
  image: node:18

  trigger:
    branch:
      - main

  environment:
    NPM_PAT: 
      type: "nosana/secret"
      endpoint: "https://secrets.k8s.dev.nos.ci"
      value: "npm-deploy-key"    
  
jobs:
  - name: "Install Dependencies"
    commands:
      - npm ci
      - npm run lint
      - npm run build
      - npm run test
      - npm run publish:public