#   _ __   ___  ___  __ _ _ __   __ _
#  | '_ \ / _ \/ __|/ _` | '_ \ / _` |
#  | | | | (_) \__ \ (_| | | | | (_| |
#  |_| |_|\___/|___/\__,_|_| |_|\__,_|

global:
  image: registry.hub.docker.com/library/node:18

  trigger:
    branch:
      - main

  environment:
    NPM_TOKEN:
      type: "nosana/secret"
      endpoint: "https://secrets.k8s.prd.nos.ci"
      value: "npm-deploy-key"
      
jobs:
  - name: "Install Dependencies"
    commands:
      - npm ci
      - npm run lint
      - npm run build
      - npm run test
      - git config --global user.email "dev@nosana.io"
      - git config --global user.name "Nosana Dev"
      - npm run publish:public
