nosana:
  description: "Template Repo Pipeline"

global:
  image: node:18

  trigger:
    branch:
      - main
      
jobs:
  - name: "Install Dependencies"
    commands:
      - npm ci
      - npm run lint
      - npm run build
