nosana:
  description: "Template Repo Pipeline"

global:
  image: node:18

  trigger:
    branch:
      - main


  environment:
    ENV: prod
    #SECRET_VALUE:
      #type: "nosana/secret"
      #endpoint: "https://secrets.k8s.dev.nos.ci"
      #value: "npm-deploy-key"

jobs:
  - name: "Install Dependencies"
    commands:
      - echo trigger ci on $ENV
      - npm ci
      - echo $PATH
      - cd /tmp
      - ls -lah
